-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS also.dim_branch
(
    branch_id serial NOT NULL,
    branch_code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    branch_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(50) COLLATE pg_catalog."default",
    extension character varying(10) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    new_date date,
    CONSTRAINT dim_branch_pkey PRIMARY KEY (branch_id),
    CONSTRAINT dim_branch_branch_code_key UNIQUE (branch_code)
);

CREATE TABLE IF NOT EXISTS also.dim_calendar
(
    date_id date NOT NULL,
    year smallint NOT NULL,
    quarter smallint NOT NULL,
    month smallint NOT NULL,
    month_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    month_short character varying(3) COLLATE pg_catalog."default" NOT NULL,
    week smallint NOT NULL,
    day_of_month smallint NOT NULL,
    day_of_week smallint NOT NULL,
    day_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    is_weekend boolean NOT NULL DEFAULT false,
    is_holiday boolean NOT NULL DEFAULT false,
    CONSTRAINT dim_calendar_pkey PRIMARY KEY (date_id)
);

CREATE TABLE IF NOT EXISTS also.dim_crane_type
(
    crane_type_id serial NOT NULL,
    crane_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    crane_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    crane_category character varying(50) COLLATE pg_catalog."default",
    application_area text COLLATE pg_catalog."default",
    purpose text COLLATE pg_catalog."default",
    is_import_substitution boolean DEFAULT false,
    technical_conditions character varying(100) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    sort_order smallint,
    created_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dim_crane_type_pkey PRIMARY KEY (crane_type_id),
    CONSTRAINT dim_crane_type_crane_code_key UNIQUE (crane_code)
);

CREATE TABLE IF NOT EXISTS also.dim_customer
(
    customer_id serial NOT NULL,
    customer_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    customer_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    short_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(300) COLLATE pg_catalog."default",
    inn character varying(12) COLLATE pg_catalog."default",
    kpp character varying(9) COLLATE pg_catalog."default",
    ogrn character varying(15) COLLATE pg_catalog."default",
    legal_address character varying(300) COLLATE pg_catalog."default",
    actual_address character varying(300) COLLATE pg_catalog."default",
    phone_primary character varying(50) COLLATE pg_catalog."default" NOT NULL,
    phone_secondary character varying(50) COLLATE pg_catalog."default",
    email_primary character varying(100) COLLATE pg_catalog."default",
    email_secondary character varying(100) COLLATE pg_catalog."default",
    contact_person character varying(150) COLLATE pg_catalog."default",
    contact_position character varying(100) COLLATE pg_catalog."default",
    manager_id integer,
    region character varying(100) COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default",
    postcode character varying(10) COLLATE pg_catalog."default",
    credit_limit numeric(15, 2) DEFAULT 0,
    payment_delay_days integer DEFAULT 0,
    discount_percent numeric(5, 2) DEFAULT 0,
    client_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Active'::character varying,
    registration_date date NOT NULL DEFAULT CURRENT_DATE,
    last_purchase_date date,
    total_purchases numeric(15, 2) DEFAULT 0,
    is_vip boolean DEFAULT false,
    is_active boolean DEFAULT true,
    created_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dim_customer_pkey PRIMARY KEY (customer_id),
    CONSTRAINT dim_customer_customer_code_key UNIQUE (customer_code)
);

CREATE TABLE IF NOT EXISTS also.dim_dealer
(
    dealer_id serial NOT NULL,
    dealer_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    short_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(200) COLLATE pg_catalog."default",
    website character varying(100) COLLATE pg_catalog."default",
    email_primary character varying(100) COLLATE pg_catalog."default",
    email_secondary character varying(100) COLLATE pg_catalog."default",
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone_primary character varying(50) COLLATE pg_catalog."default" NOT NULL,
    phone_secondary character varying(50) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    contract_date date,
    rating smallint DEFAULT 3,
    created_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dim_dealer_pkey PRIMARY KEY (dealer_id),
    CONSTRAINT dim_dealer_dealer_code_key UNIQUE (dealer_code)
);

CREATE TABLE IF NOT EXISTS also.dim_manager
(
    manager_id serial NOT NULL,
    manager_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    middle_name character varying(50) COLLATE pg_catalog."default",
    manager_name character varying(150) COLLATE pg_catalog."default" GENERATED ALWAYS AS (
CASE
    WHEN (middle_name IS NOT NULL) THEN (((((last_name)::text || ' '::text) || (first_name)::text) || ' '::text) || (middle_name)::text)
    ELSE (((last_name)::text || ' '::text) || (first_name)::text)
END) STORED,
    "position" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    department character varying(100) COLLATE pg_catalog."default" NOT NULL,
    branch_id integer,
    phone_work character varying(50) COLLATE pg_catalog."default",
    phone_mobile character varying(50) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    hire_date date NOT NULL,
    experience_years integer,
    sales_quota_year numeric(12, 2),
    manager_level character varying(20) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dim_manager_pkey PRIMARY KEY (manager_id),
    CONSTRAINT dim_manager_email_key UNIQUE (email),
    CONSTRAINT dim_manager_manager_code_key UNIQUE (manager_code)
);

CREATE TABLE IF NOT EXISTS also.dim_product
(
    product_id serial NOT NULL,
    product_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    product_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    crane_type_id integer NOT NULL,
    model character varying(100) COLLATE pg_catalog."default",
    diameter_dn smallint,
    pressure_pn smallint,
    connection_type character varying(50) COLLATE pg_catalog."default",
    bore_type character varying(50) COLLATE pg_catalog."default",
    body_material character varying(100) COLLATE pg_catalog."default",
    seal_material character varying(100) COLLATE pg_catalog."default",
    temperature_range character varying(50) COLLATE pg_catalog."default",
    weight_kg numeric(10, 2),
    length_mm integer,
    height_mm integer,
    is_active boolean DEFAULT true,
    is_stocked boolean DEFAULT true,
    retail_price numeric(12, 2),
    wholesale_price numeric(12, 2),
    created_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dim_product_pkey PRIMARY KEY (product_id),
    CONSTRAINT dim_product_product_code_key UNIQUE (product_code)
);

CREATE TABLE IF NOT EXISTS also.dim_user
(
    user_id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    manager_id integer,
    user_role character varying(50) COLLATE pg_catalog."default" DEFAULT 'Viewer'::character varying,
    is_active boolean DEFAULT true,
    last_login timestamp without time zone,
    last_activity timestamp without time zone,
    created_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT dim_user_pkey PRIMARY KEY (user_id),
    CONSTRAINT dim_user_email_key UNIQUE (email),
    CONSTRAINT dim_user_username_key UNIQUE (username),
    CONSTRAINT unique_manager_user UNIQUE (manager_id)
);

CREATE TABLE IF NOT EXISTS also.fact_sales
(
    sale_id serial NOT NULL,
    sale_date date NOT NULL,
    product_id integer NOT NULL,
    customer_id integer NOT NULL,
    dealer_id integer,
    manager_id integer NOT NULL,
    branch_id integer NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    discount_amount numeric(12, 2) DEFAULT 0,
    total_amount numeric(12, 2) GENERATED ALWAYS AS ((((quantity)::numeric * unit_price) - discount_amount)) STORED,
    payment_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Paid'::character varying,
    delivery_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Delivered'::character varying,
    invoice_number character varying(50) COLLATE pg_catalog."default",
    comment text COLLATE pg_catalog."default",
    created_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fact_sales_pkey PRIMARY KEY (sale_id)
);

CREATE TABLE IF NOT EXISTS also.file_manager_plan
(
    id serial NOT NULL,
    plan_month date NOT NULL,
    manager_full_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    plan_revenue numeric(15, 2) NOT NULL,
    plan_new_customers integer NOT NULL,
    plan_quantity integer NOT NULL,
    plan_transactions integer NOT NULL,
    file_name character varying(255) COLLATE pg_catalog."default",
    upload_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_processed boolean DEFAULT false,
    processed_date timestamp without time zone,
    error_message text COLLATE pg_catalog."default",
    CONSTRAINT file_manager_plan_pkey PRIMARY KEY (id),
    CONSTRAINT uk_file_manager_plan UNIQUE (plan_month, manager_full_name)
);

CREATE TABLE IF NOT EXISTS also.manager_sales_plan
(
    plan_id serial NOT NULL,
    manager_id integer NOT NULL,
    year integer NOT NULL,
    month integer NOT NULL,
    month_name character varying(20) COLLATE pg_catalog."default",
    plan_revenue numeric(15, 2) NOT NULL,
    plan_quantity integer NOT NULL,
    plan_transactions integer NOT NULL,
    plan_customers integer NOT NULL,
    target_growth_percent numeric(5, 2),
    plan_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Draft'::character varying,
    created_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT manager_sales_plan_pkey PRIMARY KEY (plan_id),
    CONSTRAINT uk_manager_month UNIQUE (manager_id, year, month)
);

CREATE TABLE IF NOT EXISTS also.mart_alerts_daily
(
    alert_date date,
    sale_id integer,
    sale_date date,
    invoice_number character varying(50) COLLATE pg_catalog."default",
    alert_type text COLLATE pg_catalog."default",
    priority integer,
    total_amount numeric(12, 2),
    payment_status character varying(20) COLLATE pg_catalog."default",
    delivery_status character varying(20) COLLATE pg_catalog."default",
    discount_amount numeric(12, 2),
    discount_percent numeric,
    customer_code character varying(20) COLLATE pg_catalog."default",
    customer_name character varying(150) COLLATE pg_catalog."default",
    credit_limit numeric(15, 2),
    total_purchases numeric(15, 2),
    credit_limit_usage_percent numeric,
    manager_code character varying(20) COLLATE pg_catalog."default",
    manager_name character varying(150) COLLATE pg_catalog."default",
    manager_phone character varying(50) COLLATE pg_catalog."default",
    branch_name character varying(100) COLLATE pg_catalog."default",
    branch_phone character varying(50) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS also.mart_company_plan_fact
(
    year integer,
    month integer,
    month_name character varying COLLATE pg_catalog."default",
    total_plan_revenue numeric,
    total_plan_quantity bigint,
    total_plan_transactions bigint,
    total_plan_customers bigint,
    total_fact_revenue numeric,
    total_fact_quantity numeric,
    total_fact_transactions numeric,
    total_fact_customers numeric,
    managers_with_plan bigint,
    managers_with_sales bigint,
    company_revenue_completion_percent numeric,
    managers_achieved_plan bigint,
    managers_good_performance bigint,
    achievement_rate_percent numeric
);

CREATE TABLE IF NOT EXISTS also.mart_daily_details
(
    sale_date date,
    year smallint,
    month_num smallint,
    month_name character varying(20) COLLATE pg_catalog."default",
    day_of_month smallint,
    day_name character varying(20) COLLATE pg_catalog."default",
    is_weekend boolean,
    week smallint,
    sale_id integer,
    invoice_number character varying(50) COLLATE pg_catalog."default",
    quantity integer,
    unit_price numeric(12, 2),
    discount_amount numeric(12, 2),
    total_amount numeric(12, 2),
    payment_status character varying(20) COLLATE pg_catalog."default",
    delivery_status character varying(20) COLLATE pg_catalog."default",
    product_code character varying(50) COLLATE pg_catalog."default",
    product_name character varying(200) COLLATE pg_catalog."default",
    crane_type character varying(150) COLLATE pg_catalog."default",
    diameter_dn smallint,
    pressure_pn smallint,
    connection_type character varying(50) COLLATE pg_catalog."default",
    customer_code character varying(20) COLLATE pg_catalog."default",
    customer_name character varying(150) COLLATE pg_catalog."default",
    customer_type character varying(50) COLLATE pg_catalog."default",
    customer_city character varying(100) COLLATE pg_catalog."default",
    region character varying(100) COLLATE pg_catalog."default",
    is_vip boolean,
    customer_discount numeric(5, 2),
    manager_code character varying(20) COLLATE pg_catalog."default",
    manager_name character varying(150) COLLATE pg_catalog."default",
    manager_level character varying(20) COLLATE pg_catalog."default",
    branch_code character varying(10) COLLATE pg_catalog."default",
    branch_name character varying(100) COLLATE pg_catalog."default",
    branch_city character varying(100) COLLATE pg_catalog."default",
    dealer_code character varying(20) COLLATE pg_catalog."default",
    dealer_name character varying(100) COLLATE pg_catalog."default",
    is_big_sale boolean,
    has_big_discount boolean,
    is_wholesale boolean,
    is_dealer_sale boolean
);

CREATE TABLE IF NOT EXISTS also.mart_manager_performance_monthly
(
    month_date timestamp with time zone,
    year numeric,
    month_num numeric,
    manager_id integer,
    manager_code character varying(20) COLLATE pg_catalog."default",
    manager_name character varying(150) COLLATE pg_catalog."default",
    manager_level character varying(20) COLLATE pg_catalog."default",
    department character varying(100) COLLATE pg_catalog."default",
    branch_name character varying(100) COLLATE pg_catalog."default",
    branch_id integer,
    monthly_quota numeric,
    sales_count bigint,
    units_sold bigint,
    revenue numeric,
    avg_check numeric,
    unique_customers bigint,
    dealers_attracted bigint,
    paid_sales bigint,
    revenue_paid numeric,
    overdue_sales bigint,
    unique_products_sold bigint,
    vip_customers bigint,
    unique_crane_types bigint,
    revenue_per_customer numeric,
    quota_achievement_percent text COLLATE pg_catalog."default",
    quota_status text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS also.mart_manager_plan_fact
(
    year integer,
    month integer,
    month_name character varying COLLATE pg_catalog."default",
    manager_id integer,
    manager_code character varying(20) COLLATE pg_catalog."default",
    manager_name character varying(150) COLLATE pg_catalog."default",
    manager_level character varying(20) COLLATE pg_catalog."default",
    department character varying(100) COLLATE pg_catalog."default",
    branch_name character varying(100) COLLATE pg_catalog."default",
    branch_city character varying(100) COLLATE pg_catalog."default",
    username character varying(50) COLLATE pg_catalog."default",
    plan_revenue numeric,
    plan_revenue_mln numeric,
    plan_quantity integer,
    plan_transactions integer,
    plan_customers integer,
    target_growth_percent numeric(5, 2),
    fact_revenue numeric,
    fact_revenue_mln numeric,
    fact_quantity bigint,
    fact_transactions bigint,
    fact_customers bigint,
    fact_vip_customers bigint,
    fact_discounts numeric,
    fact_avg_check numeric,
    revenue_completion_percent numeric,
    quantity_completion_percent numeric,
    transactions_completion_percent numeric,
    customers_completion_percent numeric,
    revenue_variance numeric,
    quantity_variance bigint,
    transactions_variance bigint,
    customers_variance bigint,
    plan_status text COLLATE pg_catalog."default",
    actual_avg_check numeric,
    revenue_per_customer numeric,
    calculation_date date
);

CREATE TABLE IF NOT EXISTS also.mart_monthly_kpi
(
    month_date timestamp with time zone,
    year numeric,
    month_num numeric,
    month_name character varying(20) COLLATE pg_catalog."default",
    total_transactions bigint,
    total_units_sold bigint,
    total_revenue numeric,
    revenue_mln numeric,
    total_discounts numeric,
    discount_rate_percent numeric,
    avg_check numeric,
    active_customers bigint,
    vip_customers_active bigint,
    vip_percent numeric,
    revenue_per_customer numeric,
    units_per_customer numeric,
    unique_products_sold bigint,
    unique_crane_types bigint,
    revenue_per_manager numeric,
    units_per_manager bigint,
    paid_transactions bigint,
    pending_transactions bigint,
    overdue_transactions bigint,
    cancelled_transactions bigint,
    payment_success_rate numeric,
    revenue_paid numeric,
    revenue_realized_rate numeric,
    dealer_sales bigint,
    dealer_revenue numeric,
    direct_sales bigint,
    direct_revenue numeric,
    dealer_share_percent numeric,
    branches_with_sales bigint,
    cities_served bigint,
    avg_price_per_unit numeric,
    avg_units_per_transaction numeric,
    prev_month_revenue text COLLATE pg_catalog."default",
    revenue_growth_percent text COLLATE pg_catalog."default",
    prev_month_customers text COLLATE pg_catalog."default",
    customers_growth_percent text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS also.mart_product_customer_agg
(
    sale_date date,
    product_id integer,
    customer_id integer,
    quantity integer,
    total_amount numeric(12, 2),
    product_code character varying(50) COLLATE pg_catalog."default",
    product_name character varying(200) COLLATE pg_catalog."default",
    crane_name character varying(150) COLLATE pg_catalog."default",
    product_total_sales bigint,
    product_total_revenue numeric,
    customer_code character varying(20) COLLATE pg_catalog."default",
    customer_name character varying(150) COLLATE pg_catalog."default",
    customer_type character varying(50) COLLATE pg_catalog."default",
    region character varying(100) COLLATE pg_catalog."default",
    is_vip boolean,
    customer_total_transactions bigint,
    customer_total_spent numeric,
    customer_unique_products bigint,
    first_purchase date,
    last_purchase date,
    customer_avg_check numeric,
    pct_of_customer_spent numeric,
    pct_of_product_sales numeric,
    customer_tier text COLLATE pg_catalog."default",
    product_popularity text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS also.mart_product_mix_monthly
(
    month_date timestamp with time zone,
    year numeric,
    month_num numeric,
    crane_type_id integer,
    crane_type character varying(150) COLLATE pg_catalog."default",
    is_import_substitution boolean,
    connection_type character varying(50) COLLATE pg_catalog."default",
    diameter_dn smallint,
    sales_count bigint,
    units_sold bigint,
    revenue numeric,
    avg_price numeric,
    avg_discount numeric,
    unique_customers bigint,
    unique_managers bigint,
    revenue_share_percent text COLLATE pg_catalog."default",
    rank_by_revenue text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS also.mart_regional_monthly
(
    month_date timestamp with time zone,
    year numeric,
    month_num numeric,
    branch_id integer,
    branch_name character varying(100) COLLATE pg_catalog."default",
    branch_city character varying(100) COLLATE pg_catalog."default",
    region character varying(100) COLLATE pg_catalog."default",
    customer_city character varying(100) COLLATE pg_catalog."default",
    sales_count bigint,
    units_sold bigint,
    revenue numeric,
    unique_customers bigint,
    active_managers bigint,
    active_dealers bigint,
    paid_sales bigint,
    revenue_paid numeric,
    vip_customers bigint,
    revenue_per_customer numeric
);

ALTER TABLE IF EXISTS also.dim_manager
    ADD CONSTRAINT fk_manager_branch FOREIGN KEY (branch_id)
    REFERENCES also.dim_branch (branch_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS also.dim_product
    ADD CONSTRAINT fk_product_crane_type FOREIGN KEY (crane_type_id)
    REFERENCES also.dim_crane_type (crane_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS also.dim_user
    ADD CONSTRAINT fk_user_manager FOREIGN KEY (manager_id)
    REFERENCES also.dim_manager (manager_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS unique_manager_user
    ON also.dim_user(manager_id);


ALTER TABLE IF EXISTS also.fact_sales
    ADD CONSTRAINT fk_sales_branch FOREIGN KEY (branch_id)
    REFERENCES also.dim_branch (branch_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_fact_sales_branch_id
    ON also.fact_sales(branch_id);


ALTER TABLE IF EXISTS also.fact_sales
    ADD CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id)
    REFERENCES also.dim_customer (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_fact_sales_customer_id
    ON also.fact_sales(customer_id);


ALTER TABLE IF EXISTS also.fact_sales
    ADD CONSTRAINT fk_sales_date FOREIGN KEY (sale_date)
    REFERENCES also.dim_calendar (date_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_fact_sales_date
    ON also.fact_sales(sale_date);


ALTER TABLE IF EXISTS also.fact_sales
    ADD CONSTRAINT fk_sales_dealer FOREIGN KEY (dealer_id)
    REFERENCES also.dim_dealer (dealer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_fact_sales_dealer_id
    ON also.fact_sales(dealer_id);


ALTER TABLE IF EXISTS also.fact_sales
    ADD CONSTRAINT fk_sales_product FOREIGN KEY (product_id)
    REFERENCES also.dim_product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_fact_sales_product_id
    ON also.fact_sales(product_id);

END;